pandoc \
    caratula.md \
    acuerdo.md \
    lugar.md \
    resumen.md \
    palabras_clave.md \
    abstract.md \
    keywords.md \
    introduccion.md \
    estado_del_arte.md \
    problema.md \
    solucion.md \
    impacto.md \
    metodologia.md \
    experimentacion.md \
    plan_actividades.md \
    aportes_individuales.md \
    referencias.md \
    --citeproc \
    --bibliography=references.bib \
    --number-sections \
    --csl=apa-6th-edition.csl \
    -o propuesta.pdf
