pandoc \
    caratula.md \
    aval.md \
    agradecimientos.md \
    resumen.md \
    palabras_clave.md \
    abstract.md \
    keywords.md \
    introduccion.md \
    estado_del_arte.md \
    problema.md \
    solucion.md \
    benchmarks.md \
    metodologia.md \
    herramientas.md \
    experimentacion.md \
    cronograma.md \
    riesgos.md \
    impacto.md \
    trabajos_futuros.md \
    conclusiones.md \
    aportes_individuales.md \
    referencias.md \
    anexos.md \
    --include-in-header=preamble.tex \
    --citeproc \
    --bibliography=references.bib \
    --number-sections \
    --csl=apa-6th-edition.csl \
    -o informe.pdf
